/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Error3 } from '../models/error3';

/**
 * Creates an instance of GlobalErrorResponseSchema
 */
interface GlobalErrorResponseSchema {
  errors?: Error3[];
  id?: string;
}

export class GlobalErrorResponseSchemaError extends ApiError<GlobalErrorResponseSchema> {}
