/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Error4 } from '../models/error4';

/**
 * Creates an instance of TraitMakoErrorResponse400
 */
interface TraitMakoErrorResponse400 {
  errors?: Error4[];
}

export class TraitMakoErrorResponse400Error extends ApiError<TraitMakoErrorResponse400> {}
