/**
 * NASA EPIC APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema';

/** The coordinates of the centroid are simply the average of the coordinates of the vertices. */
export interface CentroidCoordinates {
  /** latitude */
  lat: number;
  /** longitude */
  lon: number;
}

export const centroidCoordinatesSchema: Schema<CentroidCoordinates> = object({
  lat: ['lat', number()],
  lon: ['lon', number()],
});
