/**
 * NASA EPIC APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** Date object */
export interface Dates {
  /** Image date. */
  date: string;
}

export const datesSchema: Schema<Dates> = object({ date: ['date', string()] });
