/**
 * NASA EPIC APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ImageQualityEnum
 */
export enum ImageQualityEnum {
  Thumbs = 'thumbs',
  Jpg = 'jpg',
  Png = 'png',
}

/**
 * Schema for ImageQualityEnum
 */
export const imageQualityEnumSchema: Schema<ImageQualityEnum> = stringEnum(ImageQualityEnum);
