/**
 * NASA EPIC APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { Dates, datesSchema } from '../models/dates';
import {
  ImageQualityEnum,
  imageQualityEnumSchema,
} from '../models/imageQualityEnum';
import { ImagesOnADate, imagesOnADateSchema } from '../models/imagesOnADate';
import { array, number, string } from '../schema';
import { BaseController } from './baseController';

export class NaturalColorController extends BaseController {
  /**
   * This endpoint returns all the dates when images are available. The first available date is 2015-06-
   * 13, while some dates are unavailable which can be checked from this endpoint.
   *
   * @return Response from the API call
   */
  async allAvailableDates(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Dates[]>> {
    const req = this.createRequest('GET', '/api/natural/all');
    req.baseUrl('NASA');
    return req.callAsJson(array(datesSchema), requestOptions);
  }

  /**
   * This endpoint gives the list of images available on a particular date. The following information is
   * available for every image in the collection:
   *
   * image [name]
   * date
   * caption
   * centroid_coordinates
   * dscovr_j2000_position
   * lunar_j2000_position
   * sun_j2000_position
   * attitude_quaternions
   * coords
   * {
   * lat (Latitude)
   * lon (Longitude)
   * centroid_coordinates (Geographical coordinates that the satellite is looking at)
   * dscovr_j2000_position (Position of the satellite in space)
   * lunar_j2000_position   (Position of the moon in space)
   * sun_j2000_position (Position of the sun in space)
   * attitude_quaternions   (Satellite attitude)
   * }
   *
   * @param date The date the image was published.
   * @return Response from the API call
   */
  async imageListOnADate(
    date: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ImagesOnADate[]>> {
    const req = this.createRequest('GET');
    req.baseUrl('NASA');
    const mapped = req.prepareArgs({ date: [date, string()] });
    req.appendTemplatePath`/api/natural/date/${mapped.date}`;
    return req.callAsJson(array(imagesOnADateSchema), requestOptions);
  }

  /**
   * All of the imagery is stored in an archival directory subdivided by collection, year, month, day,
   * and image type. There are three separate image types available: full resolution PNG, half-resolution
   * JPG, and thumbnails.
   *
   * @param year         The year on which the image was published.
   * @param month        The month on which the image was published.
   * @param day          The day on which the image was published.
   * @param imageTitle   Image Title can be obtained from "Image List On A Date" endpoint. Please
   *                                         append .png (for PNG) or .jpg (for JPG and Thumbnails).
   * @param imageQuality There are three separate image types available: full resolution PNG, half-
   *                                         resolution JPG, and thumbnails
   * @return Response from the API call
   */
  async singleImageinPNG(
    year: string,
    month: string,
    day: string,
    imageTitle: string,
    imageQuality: ImageQualityEnum,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<NodeJS.ReadableStream | Blob>> {
    const req = this.createRequest('GET');
    req.baseUrl('NASA');
    const mapped = req.prepareArgs({
      year: [year, string()],
      month: [month, string()],
      day: [day, string()],
      imageTitle: [imageTitle, string()],
      imageQuality: [imageQuality, imageQualityEnumSchema],
    });
    req.appendTemplatePath`/archive/natural/${mapped.year}/${mapped.month}/${mapped.day}/${mapped.imageTitle}/${mapped.imageQuality}`;
    return req.callAsStream(requestOptions);
  }

  /**
   * This endpoint provides combined images of a single day. Please note that DSCOVR started operation in
   * 2015. Some dates are unavailable while DSCOVR went to maintenance etc. The endpoint "All Available
   * Dates" can help getting a list of all the available dates.
   *
   * @param date         All available images on this date would be displayed. Date pattern needs
   *                                         to be in yyyy-mm-dd format.
   * @param gridColumns  Number of earth positions displayed per row
   * @param imageQuality Quality of the Image being displayed. Thumbnail is of the lowest quality,
   *                                         but is the quickest to load. The Best quality images in PNG could take up
   *                                         to a minute to load
   * @return Response from the API call
   */
  async combinedImagesOnADate(
    date: string,
    gridColumns: number,
    imageQuality: ImageQualityEnum,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<NodeJS.ReadableStream | Blob>> {
    const req = this.createRequest('GET');
    req.baseUrl('apimatic');
    const mapped = req.prepareArgs({
      date: [date, string()],
      gridColumns: [gridColumns, number()],
      imageQuality: [imageQuality, imageQualityEnumSchema],
    });
    req.appendTemplatePath`/imagescollage/${mapped.date}/${mapped.gridColumns}/${mapped.imageQuality}`;
    return req.callAsStream(requestOptions);
  }
}
