/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AndOrEnum
 */
export enum AndOrEnum {
  And = 'and',
  Or = 'or',
}

/**
 * Schema for AndOrEnum
 */
export const andOrEnumSchema: Schema<AndOrEnum> = stringEnum(AndOrEnum);
