/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, number, object, optional, Schema } from '../schema';

/** An object allowing you to specify how to handle unsubscribes. */
export interface Asm {
  /** The unsubscribe group to associate with this email. */
  groupId: number;
  /** An array containing the unsubscribe groups that you would like to be displayed on the unsubscribe preferences page. */
  groupsToDisplay?: number[];
}

export const asmSchema: Schema<Asm> = object({
  groupId: ['group_id', number()],
  groupsToDisplay: ['groups_to_display', optional(array(number()))],
});
