/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface CCBCCEmailObject {
  /** The intended recipient's email address. */
  email: string;
  /** The intended recipient's name. */
  name?: string;
}

export const cCBCCEmailObjectSchema: Schema<CCBCCEmailObject> = object({
  email: ['email', string()],
  name: ['name', optional(string())],
});
