/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';

/** Allows you to track if a recipient clicked a link in your email. */
export interface ClickTracking {
  /** Indicates if this setting is enabled. */
  enable?: boolean;
  /** Indicates if this setting should be included in the `text/plain` portion of your email. */
  enableText?: boolean;
}

export const clickTrackingSchema: Schema<ClickTracking> = object({
  enable: ['enable', optional(boolean())],
  enableText: ['enable_text', optional(boolean())],
});
