/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { AndOrEnum, andOrEnumSchema } from './andOrEnum';
import { OperatorEnum, operatorEnumSchema } from './operatorEnum';

export interface ContactDBSegmentsConditions {
  field: string;
  value: string;
  operator: OperatorEnum;
  andOr?: AndOrEnum;
}

export const contactDBSegmentsConditionsSchema: Schema<ContactDBSegmentsConditions> = object(
  {
    field: ['field', string()],
    value: ['value', string()],
    operator: ['operator', operatorEnumSchema],
    andOr: ['and_or', optional(andOrEnumSchema)],
  }
);
