/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';
import { TypeEnum, typeEnumSchema } from './typeEnum';

export interface ContactDBCustomFieldSchemaWithID {
  /** The name of the field */
  name?: string;
  /** The type of the field. */
  type?: TypeEnum;
  /** The ID of the custom field. */
  id?: number;
}

export const contactDBCustomFieldSchemaWithIDSchema: Schema<ContactDBCustomFieldSchemaWithID> = object(
  {
    name: ['name', optional(string())],
    type: ['type', optional(typeEnumSchema)],
    id: ['id', optional(number())],
  }
);
