/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  ContactDBSegmentsConditions,
  contactDBSegmentsConditionsSchema,
} from './contactDBSegmentsConditions';

export interface CreateASegmentRequest {
  /** The name of this segment. */
  name: string;
  /** The list id from which to make this segment. Not including this ID will mean your segment is created from the main contactdb rather than a list. */
  listId?: number;
  /** The conditions for a recipient to be included in this segment. */
  conditions: ContactDBSegmentsConditions[];
  /** The count of recipients in this list. This is not included on creation of segments. */
  recipientCount?: number;
}

export const createASegmentRequestSchema: Schema<CreateASegmentRequest> = object(
  {
    name: ['name', string()],
    listId: ['list_id', optional(number())],
    conditions: [
      'conditions',
      array(lazy(() => contactDBSegmentsConditionsSchema)),
    ],
    recipientCount: ['recipient_count', optional(number())],
  }
);
