/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, boolean, object, optional, Schema, string } from '../schema';
import { EditorEnum, editorEnumSchema } from './editorEnum';

export interface DesignCommonFields {
  /** The name of the new design. */
  name?: string;
  /** The editor used in the UI. */
  editor?: EditorEnum;
  /** If true, plain_content is always generated from html_content. If false, plain_content is not altered. */
  generatePlainContent?: boolean;
  /** Subject of the Design. */
  subject?: string;
  /** The list of categories applied to the design */
  categories?: string[];
}

export const designCommonFieldsSchema: Schema<DesignCommonFields> = object({
  name: ['name', optional(string())],
  editor: ['editor', optional(editorEnumSchema)],
  generatePlainContent: ['generate_plain_content', optional(boolean())],
  subject: ['subject', optional(string())],
  categories: ['categories', optional(array(string()))],
});
