/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DispositionEnum
 */
export enum DispositionEnum {
  Inline = 'inline',
  Attachment = 'attachment',
}

/**
 * Schema for DispositionEnum
 */
export const dispositionEnumSchema: Schema<DispositionEnum> = stringEnum(DispositionEnum);
