/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, Schema, string } from '../schema';

/** A DNS record. */
export interface Dkim1 {
  /** Indicates if this is a valid DNS record. */
  valid: boolean;
  /** The type of DNS record. */
  type: string;
  /** The domain that this DNS record was created for. */
  host: string;
  /** The DNS record. */
  data: string;
}

export const dkim1Schema: Schema<Dkim1> = object({
  valid: ['valid', boolean()],
  type: ['type', string()],
  host: ['host', string()],
  data: ['data', string()],
});
