/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Dkim1, dkim1Schema } from './dkim1';
import { MailCname, mailCnameSchema } from './mailCname';

/** The DNS records used to authenticate the sending domain. */
export interface Dns {
  /** The CNAME for your sending domain that points to sendgrid.net. */
  mailCname: MailCname;
  /** A DNS record. */
  dkim1: Dkim1;
  /** A DNS record. */
  dkim2: Dkim1;
}

export const dnsSchema: Schema<Dns> = object({
  mailCname: ['mail_cname', lazy(() => mailCnameSchema)],
  dkim1: ['dkim1', lazy(() => dkim1Schema)],
  dkim2: ['dkim2', lazy(() => dkim1Schema)],
});
