/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  Schema,
  string,
} from '../schema';
import { Dns, dnsSchema } from './dns';

export interface DomainAuthenticationMandatorySubdomain {
  /** The ID of the authenticated domain. */
  id: number;
  /** The ID of the user that this domain is associated with. */
  userId: number;
  /** The subdomain to use for this authenticated domain. */
  subdomain: string;
  /** The domain to be authenticated. */
  domain: string;
  /** The username that this domain will be associated with. */
  username: string;
  /** The IPs to be included in the custom SPF record for this authenticated domain. */
  ips: string[];
  /** Indicates whether this authenticated domain uses custom SPF. */
  customSpf: boolean;
  /** Indicates if this is the default authenticated domain. */
  mDefault: boolean;
  /** Indicates if this authenticated domain was created using the legacy whitelabel tool. If it is a legacy whitelabel, it will still function, but you'll need to create a new authenticated domain if you need to update it. */
  legacy: boolean;
  /** Indicates if this authenticated domain uses automated security. */
  automaticSecurity: boolean;
  /** Indicates if this is a valid authenticated domain. */
  valid: boolean;
  /** The DNS records used to authenticate the sending domain. */
  dns: Dns;
}

export const domainAuthenticationMandatorySubdomainSchema: Schema<DomainAuthenticationMandatorySubdomain> = object(
  {
    id: ['id', number()],
    userId: ['user_id', number()],
    subdomain: ['subdomain', string()],
    domain: ['domain', string()],
    username: ['username', string()],
    ips: ['ips', array(string())],
    customSpf: ['custom_spf', boolean()],
    mDefault: ['default', boolean()],
    legacy: ['legacy', boolean()],
    automaticSecurity: ['automatic_security', boolean()],
    valid: ['valid', boolean()],
    dns: ['dns', lazy(() => dnsSchema)],
  }
);
