/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { Error2, error2Schema } from './error2';

/** If the request is incorrect, an array of errors will be returned. */
export interface ErrorsSeg {
  errors: Error2[];
}

export const errorsSegSchema: Schema<ErrorsSeg> = object({
  errors: ['errors', array(lazy(() => error2Schema))],
});
