/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Error2 {
  /** the field in the request body that is incorrect */
  field: string;
  /** a description of what is specifically wrong with the field passed in the request */
  message: string;
}

export const error2Schema: Schema<Error2> = object({
  field: ['field', string()],
  message: ['message', string()],
});
