/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Error {
  message: string;
  field: string;
  errorId: string;
}

export const errorSchema: Schema<Error> = object({
  message: ['message', string()],
  field: ['field', string()],
  errorId: ['error_id', string()],
});
