/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema';

export interface Error4 {
  /** The ID associated with the error. */
  errorId?: string;
  /** The field that generated the error. */
  field?: string | null;
  /** The error message. */
  message: string;
  parameter?: string;
}

export const error4Schema: Schema<Error4> = object({
  errorId: ['error_id', optional(string())],
  field: ['field', optional(nullable(string()))],
  message: ['message', string()],
  parameter: ['parameter', optional(string())],
});
