/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface FromEmailObject {
  /** The 'From' email address used to deliver the message. This address should be a verified sender in your Twilio SendGrid account. */
  email: string;
  /** A name or title associated with the sending email address. */
  name?: string;
}

export const fromEmailObjectSchema: Schema<FromEmailObject> = object({
  email: ['email', string()],
  name: ['name', optional(string())],
});
