/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

/** Allows you to enable tracking provided by Google Analytics. */
export interface Ganalytics {
  /** Indicates if this setting is enabled. */
  enable?: boolean;
  /** Name of the referrer source. (e.g. Google, SomeDomain.com, or Marketing Email) */
  utmSource?: string;
  /** Name of the marketing medium. (e.g. Email) */
  utmMedium?: string;
  /** Used to identify any paid keywords. */
  utmTerm?: string;
  /** Used to differentiate your campaign from advertisements. */
  utmContent?: string;
  /** The name of the campaign. */
  utmCampaign?: string;
}

export const ganalyticsSchema: Schema<Ganalytics> = object({
  enable: ['enable', optional(boolean())],
  utmSource: ['utm_source', optional(string())],
  utmMedium: ['utm_medium', optional(string())],
  utmTerm: ['utm_term', optional(string())],
  utmContent: ['utm_content', optional(string())],
  utmCampaign: ['utm_campaign', optional(string())],
});
