/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  BypassBounceManagement,
  bypassBounceManagementSchema,
} from './bypassBounceManagement';
import {
  BypassListManagement,
  bypassListManagementSchema,
} from './bypassListManagement';
import {
  BypassSpamManagement,
  bypassSpamManagementSchema,
} from './bypassSpamManagement';
import {
  BypassUnsubscribeManagement,
  bypassUnsubscribeManagementSchema,
} from './bypassUnsubscribeManagement';
import { Footer, footerSchema } from './footer';
import { SandboxMode, sandboxModeSchema } from './sandboxMode';

/** A collection of different mail settings that you can use to specify how you would like this email to be handled. */
export interface MailSettings {
  /** Allows you to bypass all unsubscribe groups and suppressions to ensure that the email is delivered to every single recipient. This should only be used in emergencies when it is absolutely necessary that every recipient receives your email. This filter cannot be combined with any other bypass filters. See our [documentation](https://sendgrid.com/docs/ui/sending-email/index-suppressions/#bypass-suppressions) for more about bypass filters. */
  bypassListManagement?: BypassListManagement;
  /** Allows you to bypass the spam report list to ensure that the email is delivered to recipients. Bounce and unsubscribe lists will still be checked; addresses on these other lists will not receive the message. This filter cannot be combined with the `bypass_list_management` filter. See our [documentation](https://sendgrid.com/docs/ui/sending-email/index-suppressions/#bypass-suppressions) for more about bypass filters. */
  bypassSpamManagement?: BypassSpamManagement;
  /** Allows you to bypass the bounce list to ensure that the email is delivered to recipients. Spam report and unsubscribe lists will still be checked; addresses on these other lists will not receive the message. This filter cannot be combined with the `bypass_list_management` filter. See our [documentation](https://sendgrid.com/docs/ui/sending-email/index-suppressions/#bypass-suppressions) for more about bypass filters. */
  bypassBounceManagement?: BypassBounceManagement;
  /** Allows you to bypass the global unsubscribe list to ensure that the email is delivered to recipients. Bounce and spam report lists will still be checked; addresses on these other lists will not receive the message. This filter applies only to global unsubscribes and will not bypass group unsubscribes. This filter cannot be combined with the `bypass_list_management` filter. See our [documentation](https://sendgrid.com/docs/ui/sending-email/index-suppressions/#bypass-suppressions) for more about bypass filters. */
  bypassUnsubscribeManagement?: BypassUnsubscribeManagement;
  /** The default footer that you would like included on every email. */
  footer?: Footer;
  /** Sandbox Mode allows you to send a test email to ensure that your request body is valid and formatted correctly. */
  sandboxMode?: SandboxMode;
}

export const mailSettingsSchema: Schema<MailSettings> = object({
  bypassListManagement: [
    'bypass_list_management',
    optional(lazy(() => bypassListManagementSchema)),
  ],
  bypassSpamManagement: [
    'bypass_spam_management',
    optional(lazy(() => bypassSpamManagementSchema)),
  ],
  bypassBounceManagement: [
    'bypass_bounce_management',
    optional(lazy(() => bypassBounceManagementSchema)),
  ],
  bypassUnsubscribeManagement: [
    'bypass_unsubscribe_management',
    optional(lazy(() => bypassUnsubscribeManagementSchema)),
  ],
  footer: ['footer', optional(lazy(() => footerSchema))],
  sandboxMode: ['sandbox_mode', optional(lazy(() => sandboxModeSchema))],
});
