/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, nullable, object, optional, Schema, string } from '../schema';

export interface MailSettingsForwardBounce {
  /** The email address that you would like your bounce reports forwarded to. */
  email?: string | null;
  /** Indicates if the bounce forwarding mail setting is enabled. */
  enabled?: boolean;
}

export const mailSettingsForwardBounceSchema: Schema<MailSettingsForwardBounce> = object(
  {
    email: ['email', optional(nullable(string()))],
    enabled: ['enabled', optional(boolean())],
  }
);
