/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

export interface MailSettingsForwardSpam {
  /** The email address where you would like the spam reports to be forwarded. */
  email?: string;
  /** Indicates if the Forward Spam setting is enabled. */
  enabled?: boolean;
}

export const mailSettingsForwardSpamSchema: Schema<MailSettingsForwardSpam> = object(
  {
    email: ['email', optional(string())],
    enabled: ['enabled', optional(boolean())],
  }
);
