/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, Schema, string } from '../schema';

/** The CNAME for your sending domain that points to sendgrid.net. */
export interface MailCname {
  /** Indicates if this is a valid CNAME. */
  valid: boolean;
  /** The type of DNS record. */
  type: string;
  /** The domain that this CNAME is created for. */
  host: string;
  /** The CNAME record. */
  data: string;
}

export const mailCnameSchema: Schema<MailCname> = object({
  valid: ['valid', boolean()],
  type: ['type', string()],
  host: ['host', string()],
  data: ['data', string()],
});
