/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, boolean, object, optional, Schema, string } from '../schema';

export interface MailSettingsAddressWhitelabel {
  /** Indicates if you have an email address whitelist enabled. */
  enabled?: boolean;
  /** All email addresses that are currently on the whitelist. */
  list?: string[];
}

export const mailSettingsAddressWhitelabelSchema: Schema<MailSettingsAddressWhitelabel> = object(
  {
    enabled: ['enabled', optional(boolean())],
    list: ['list', optional(array(string()))],
  }
);
