/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface Metadata1 {
  prev?: string;
  self?: string;
  next?: string;
  count?: number;
}

export const metadata1Schema: Schema<Metadata1> = object({
  prev: ['prev', optional(string())],
  self: ['self', optional(string())],
  next: ['next', optional(string())],
  count: ['count', optional(number())],
});
