/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface Metadata {
  /** The URL of the previous page of results. If this field isn't present, you're at the start of the list. */
  prev?: string;
  /** The URL of the current page of results. */
  self?: string;
  /** The URL of the next page of results. If this field isn't present, you're at the end of the list. */
  next?: string;
  /** The number of items in the entire list, i.e., across all pages. */
  count?: number;
}

export const metadataSchema: Schema<Metadata> = object({
  prev: ['prev', optional(string())],
  self: ['self', optional(string())],
  next: ['next', optional(string())],
  count: ['count', optional(number())],
});
