/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OperatorEnum
 */
export enum OperatorEnum {
  Eq = 'eq',
  Ne = 'ne',
  Lt = 'lt',
  Gt = 'gt',
  Contains = 'contains',
}

/**
 * Schema for OperatorEnum
 */
export const operatorEnumSchema: Schema<OperatorEnum> = stringEnum(OperatorEnum);
