/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { CCBCCEmailObject, cCBCCEmailObjectSchema } from './cCBCCEmailObject';
import { FromEmailObject, fromEmailObjectSchema } from './fromEmailObject';

export interface Personalization {
  from?: FromEmailObject;
  to: CCBCCEmailObject[];
  /** An array of recipients who will receive a copy of your email. Each object in this array must contain the recipient's email address. Each object in the array may optionally contain the recipient's name. */
  cc?: CCBCCEmailObject[];
  /** An array of recipients who will receive a blind carbon copy of your email. Each object in this array must contain the recipient's email address. Each object in the array may optionally contain the recipient's name. */
  bcc?: CCBCCEmailObject[];
  /** The subject of your email. See character length requirements according to [RFC 2822](http://stackoverflow.com/questions/1592291/what-is-the-email-subject-length-limit#answer-1592310). */
  subject?: string;
  /** A collection of JSON key/value pairs allowing you to specify handling instructions for your email. You may not overwrite the following headers: `x-sg-id`, `x-sg-eid`, `received`, `dkim-signature`, `Content-Type`, `Content-Transfer-Encoding`, `To`, `From`, `Subject`, `Reply-To`, `CC`, `BCC` */
  headers?: unknown;
  /** Substitutions allow you to insert data without using Dynamic Transactional Templates. This field should **not** be used in combination with a Dynamic Transactional Template, which can be identified by a `template_id` starting with `d-`. This field is a collection of key/value pairs following the pattern "substitution_tag":"value to substitute". The key/value pairs must be strings. These substitutions will apply to the text and html content of the body of your email, in addition to the `subject` and `reply-to` parameters. The total collective size of your substitutions may not exceed 10,000 bytes per personalization object. */
  substitutions?: unknown;
  /** Dynamic template data is available using Handlebars syntax in Dynamic Transactional Templates. This field should be used in combination with a Dynamic Transactional Template, which can be identified by a `template_id` starting with `d-`. This field is a collection of key/value pairs following the pattern "variable_name":"value to insert". */
  dynamicTemplateData?: unknown;
  /** Values that are specific to this personalization that will be carried along with the email and its activity data. Substitutions will not be made on custom arguments, so any string that is entered into this parameter will be assumed to be the custom argument that you would like to be used. This field may not exceed 10,000 bytes. */
  customArgs?: unknown;
  /** A unix timestamp allowing you to specify when your email should be delivered. Scheduling delivery more than 72 hours in advance is forbidden. */
  sendAt?: number;
}

export const personalizationSchema: Schema<Personalization> = object({
  from: ['from', optional(lazy(() => fromEmailObjectSchema))],
  to: ['to', array(lazy(() => cCBCCEmailObjectSchema))],
  cc: ['cc', optional(array(lazy(() => cCBCCEmailObjectSchema)))],
  bcc: ['bcc', optional(array(lazy(() => cCBCCEmailObjectSchema)))],
  subject: ['subject', optional(string())],
  headers: ['headers', optional(unknown())],
  substitutions: ['substitutions', optional(unknown())],
  dynamicTemplateData: ['dynamic_template_data', optional(unknown())],
  customArgs: ['custom_args', optional(unknown())],
  sendAt: ['send_at', optional(number())],
});
