/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';

/** Sandbox Mode allows you to send a test email to ensure that your request body is valid and formatted correctly. */
export interface SandboxMode {
  /** Indicates if this setting is enabled. */
  enable?: boolean;
}

export const sandboxModeSchema: Schema<SandboxMode> = object({
  enable: ['enable', optional(boolean())],
});
