/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface SegmentSummary {
  id: string;
  contactsCount: number;
  /** ISO8601 of created timestamp */
  createdAt: string;
  name?: string;
  /** The id of the list if this segment is a child of a list.  This implies the query `AND CONTAINS(list_ids, ${parent_list_id})` */
  parentListId?: string;
  /** ISO8601 timestamp the sample was last updated */
  sampleUpdatedAt: string;
  /** ISO8601 timestamp the object was last updated */
  updatedAt: string;
  /** ISO8601 string that is equal to `sample_updated_at` plus an internally calculated offset that depends on how often contacts enter or exit segments as the scheduled pipeline updates the samples. */
  nextSampleUpdate?: string;
}

export const segmentSummarySchema: Schema<SegmentSummary> = object({
  id: ['id', string()],
  contactsCount: ['contacts_count', number()],
  createdAt: ['created_at', string()],
  name: ['name', optional(string())],
  parentListId: ['parent_list_id', optional(string())],
  sampleUpdatedAt: ['sample_updated_at', string()],
  updatedAt: ['updated_at', string()],
  nextSampleUpdate: ['next_sample_update', optional(string())],
});
