/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

export interface SegmentWrite {
  /** Name of the segment. */
  name: string;
  /** The array of list ids to filter contacts on when building this segment. It allows only one such list id for now. We will support more in future */
  parentListIds?: string[];
  /** SQL query which will filter contacts based on the conditions provided */
  queryDsl: string;
}

export const segmentWriteSchema: Schema<SegmentWrite> = object({
  name: ['name', string()],
  parentListIds: ['parent_list_ids', optional(array(string()))],
  queryDsl: ['query_dsl', string()],
});
