/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface SelfMetadata {
  /** A link to this object. */
  self?: string;
}

export const selfMetadataSchema: Schema<SelfMetadata> = object({
  self: ['self', optional(string())],
});
