/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

export interface SingleSingOnTeammateCommonFields {
  /** The Teammate’s first name. */
  firstName: string;
  /** The Teammate’s last name. */
  lastName: string;
  /** The Teammate’s email address. This email address will also function as the Teammate’s username and must match the address assigned to the user in your IdP. This address cannot be changed after the Teammate is created. */
  email: string;
  /** Indicates if the Teammate has admin permissions. */
  isAdmin?: boolean;
  /** Indicates if the Teammate has read_only permissions. */
  isReadOnly?: boolean;
}

export const singleSingOnTeammateCommonFieldsSchema: Schema<SingleSingOnTeammateCommonFields> = object(
  {
    firstName: ['first_name', string()],
    lastName: ['last_name', string()],
    email: ['email', string()],
    isAdmin: ['is_admin', optional(boolean())],
    isReadOnly: ['is_read_only', optional(boolean())],
  }
);
