/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

/** Allows you to insert a subscription management link at the bottom of the text and HTML bodies of your email. If you would like to specify the location of the link within your email, you may use the `substitution_tag`. */
export interface SubscriptionTracking {
  /** Indicates if this setting is enabled. */
  enable?: boolean;
  /** Text to be appended to the email with the subscription tracking link. You may control where the link is by using the tag <% %> */
  text?: string;
  /** HTML to be appended to the email with the subscription tracking link. You may control where the link is by using the tag <% %> */
  html?: string;
  /** A tag that will be replaced with the unsubscribe URL. for example: `[unsubscribe_url]`. If this parameter is used, it will override both the `text` and `html` parameters. The URL of the link will be placed at the substitution tag’s location with no additional formatting. */
  substitutionTag?: string;
}

export const subscriptionTrackingSchema: Schema<SubscriptionTracking> = object({
  enable: ['enable', optional(boolean())],
  text: ['text', optional(string())],
  html: ['html', optional(string())],
  substitutionTag: ['substitution_tag', optional(string())],
});
