/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { ClickTracking, clickTrackingSchema } from './clickTracking';
import { Ganalytics, ganalyticsSchema } from './ganalytics';
import { OpenTracking, openTrackingSchema } from './openTracking';
import {
  SubscriptionTracking,
  subscriptionTrackingSchema,
} from './subscriptionTracking';

/** Settings to determine how you would like to track the metrics of how your recipients interact with your email. */
export interface TrackingSettings {
  /** Allows you to track if a recipient clicked a link in your email. */
  clickTracking?: ClickTracking;
  /** Allows you to track if the email was opened by including a single pixel image in the body of the content. When the pixel is loaded, Twilio SendGrid can log that the email was opened. */
  openTracking?: OpenTracking;
  /** Allows you to insert a subscription management link at the bottom of the text and HTML bodies of your email. If you would like to specify the location of the link within your email, you may use the `substitution_tag`. */
  subscriptionTracking?: SubscriptionTracking;
  /** Allows you to enable tracking provided by Google Analytics. */
  ganalytics?: Ganalytics;
}

export const trackingSettingsSchema: Schema<TrackingSettings> = object({
  clickTracking: ['click_tracking', optional(lazy(() => clickTrackingSchema))],
  openTracking: ['open_tracking', optional(lazy(() => openTrackingSchema))],
  subscriptionTracking: [
    'subscription_tracking',
    optional(lazy(() => subscriptionTrackingSchema)),
  ],
  ganalytics: ['ganalytics', optional(lazy(() => ganalyticsSchema))],
});
