/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { Asm, asmSchema } from './asm';
import { Attachment, attachmentSchema } from './attachment';
import { Content, contentSchema } from './content';
import { FromEmailObject, fromEmailObjectSchema } from './fromEmailObject';
import { MailSettings, mailSettingsSchema } from './mailSettings';
import { Personalization, personalizationSchema } from './personalization';
import {
  ReplyToEmailObject,
  replyToEmailObjectSchema,
} from './replyToEmailObject';
import { ReplyToList, replyToListSchema } from './replyToList';
import { TrackingSettings, trackingSettingsSchema } from './trackingSettings';

export interface V3MailSendRequest {
  /** An array of messages and their metadata. Each object within personalizations can be thought of as an envelope - it defines who should receive an individual message and how that message should be handled. See our [Personalizations documentation](https://sendgrid.com/docs/for-developers/sending-email/personalizations/) for examples. */
  personalizations: Personalization[];
  from: FromEmailObject;
  replyTo?: ReplyToEmailObject;
  /** An array of recipients who will receive replies and/or bounces. Each object in this array must contain the recipient's email address. Each object in the array may optionally contain the recipient's name. You can either choose to use “reply_to” field or “reply_to_list” but not both. */
  replyToList?: ReplyToList[];
  /** The global or 'message level' subject of your email. This may be overridden by subject lines set in personalizations. */
  subject: string;
  /** An array where you can specify the content of your email. You can include multiple [MIME types](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types) of content, but you must specify at least one MIME type. To include more than one MIME type, add another object to the array containing the `type` and `value` parameters. */
  content: Content[];
  /** An array of objects where you can specify any attachments you want to include. */
  attachments?: Attachment[];
  /** An email template ID. A template that contains a subject and content — either text or html — will override any subject and content values specified at the personalizations or message level. */
  templateId?: string;
  /** An object containing key/value pairs of header names and the value to substitute for them. The key/value pairs must be strings. You must ensure these are properly encoded if they contain unicode characters. These headers cannot be one of the reserved headers. */
  headers?: unknown;
  /** An array of category names for this message. Each category name may not exceed 255 characters. */
  categories?: string[];
  /** Values that are specific to the entire send that will be carried along with the email and its activity data.  Key/value pairs must be strings. Substitutions will not be made on custom arguments, so any string that is entered into this parameter will be assumed to be the custom argument that you would like to be used. This parameter is overridden by `custom_args` set at the personalizations level. Total `custom_args` size may not exceed 10,000 bytes. */
  customArgs?: string;
  /** A unix timestamp allowing you to specify when you want your email to be delivered. This may be overridden by the `send_at` parameter set at the personalizations level. Delivery cannot be scheduled more than 72 hours in advance. If you have the flexibility, it's better to schedule mail for off-peak times. Most emails are scheduled and sent at the top of the hour or half hour. Scheduling email to avoid peak times — for example, scheduling at 10:53 — can result in lower deferral rates due to the reduced traffic during off-peak times. */
  sendAt?: number;
  /** An ID representing a batch of emails to be sent at the same time. Including a `batch_id` in your request allows you include this email in that batch. It also enables you to cancel or pause the delivery of that batch. For more information, see the [Cancel Scheduled Sends API](https://sendgrid.com/docs/api-reference/). */
  batchId?: string;
  /** An object allowing you to specify how to handle unsubscribes. */
  asm?: Asm;
  /** The IP Pool that you would like to send this email from. */
  ipPoolName?: string;
  /** A collection of different mail settings that you can use to specify how you would like this email to be handled. */
  mailSettings?: MailSettings;
  /** Settings to determine how you would like to track the metrics of how your recipients interact with your email. */
  trackingSettings?: TrackingSettings;
}

export const v3MailSendRequestSchema: Schema<V3MailSendRequest> = object({
  personalizations: [
    'personalizations',
    array(lazy(() => personalizationSchema)),
  ],
  from: ['from', lazy(() => fromEmailObjectSchema)],
  replyTo: ['reply_to', optional(lazy(() => replyToEmailObjectSchema))],
  replyToList: [
    'reply_to_list',
    optional(array(lazy(() => replyToListSchema))),
  ],
  subject: ['subject', string()],
  content: ['content', array(lazy(() => contentSchema))],
  attachments: ['attachments', optional(array(lazy(() => attachmentSchema)))],
  templateId: ['template_id', optional(string())],
  headers: ['headers', optional(unknown())],
  categories: ['categories', optional(array(string()))],
  customArgs: ['custom_args', optional(string())],
  sendAt: ['send_at', optional(number())],
  batchId: ['batch_id', optional(string())],
  asm: ['asm', optional(lazy(() => asmSchema))],
  ipPoolName: ['ip_pool_name', optional(string())],
  mailSettings: ['mail_settings', optional(lazy(() => mailSettingsSchema))],
  trackingSettings: [
    'tracking_settings',
    optional(lazy(() => trackingSettingsSchema)),
  ],
});
