/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { Result, resultSchema } from './result';

export interface V3MailSettingsResponse {
  /** The list of all mail settings. */
  result: Result[];
}

export const v3MailSettingsResponseSchema: Schema<V3MailSettingsResponse> = object(
  { result: ['result', array(lazy(() => resultSchema))] }
);
