/**
 * Twilio SendGrid v3 APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, boolean, object, optional, Schema, string } from '../schema';

export interface V3MailSettingsAddressWhitelistRequest {
  /** Indicates if your email address whitelist is enabled. */
  enabled?: boolean;
  /** Either a single email address that you want whitelisted or a domain, for which all email addresses belonging to this domain will be whitelisted. */
  list?: string[];
}

export const v3MailSettingsAddressWhitelistRequestSchema: Schema<V3MailSettingsAddressWhitelistRequest> = object(
  {
    enabled: ['enabled', optional(boolean())],
    list: ['list', optional(array(string()))],
  }
);
