/**
 * NASA EPIC APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema';

export interface CentroidCoordinates {
  lat: number;
  lon: number;
}

export const centroidCoordinatesSchema: Schema<CentroidCoordinates> = object({
  lat: ['lat', number()],
  lon: ['lon', number()],
});
