/**
 * NASA EPIC APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SolarEclipseDatesEnum
 */
export enum SolarEclipseDatesEnum {
  TotalEclipseMarch2016 = '2016-03-09',
  TotalEclipseAugust2017 = '2017-08-21',
}

/**
 * Schema for SolarEclipseDatesEnum
 */
export const solarEclipseDatesEnumSchema: Schema<SolarEclipseDatesEnum> = stringEnum(SolarEclipseDatesEnum);
